# Subreddit to monitor
Subreddit = "QOTSA"

# Discord Webhook to send posts to
DiscordWebhookURL = "https://discord.com/api/webhooks/979330018817744916/aMlf1bhHDMRYkpsWrwNB4oajshZ4pbrtAcBC3Ih7VFc3sgj7jfwHIL-Gr54p4mBUtH2e"

# URL for icon to embed in the Discord message
IconURL = "https://i.imgur.com/3NtinwD.png"

# Reddit OAuth Client & Secret
# To create these, go to https://www.reddit.com/prefs/apps/
# Scroll to bottom and click "are you a developer? create an app.."
# And select "Web app"

# NOTE: these examples have been invalidated
RedditOAClient = "j5oJ9o-v2GPrwMk_v5RVFg"
RedditOASecret = "Ghf6fe9ya-ee9ePKYYKbqodRhaS-fQ"

# Reddit Username & Password
RedditUsername = "RedditUser1"
RedditPassword = "passwd"