name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Get binary name
      id: bin
      run: echo "##[set-output name=binfile;]$(find . -maxdepth 1 -type f -executable | cut -c 3-)"

    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.3
      with:
          name: ${{ steps.bin.outputs.binfile }}
          path: ${{ steps.bin.outputs.binfile }}